<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <packaging>jar</packaging>

  <parent>
    <groupId>org.example</groupId>
    <artifactId>plugin</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <groupId>org.example.plugin</groupId>
  <artifactId>app</artifactId>

  <dependencies>
    <dependency>
      <groupId>org.example.plugin</groupId>
      <artifactId>api</artifactId>
      <version>${project.parent.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includeSystemScope>true</includeSystemScope>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <id>copy-plugins</id>
            <phase>package</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.example.plugin</groupId>
                  <artifactId>plugin-hello</artifactId>
                  <version>${project.parent.version}</version>
                  <outputDirectory>${project.build.directory}/plugins</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>org.example.plugin</groupId>
                  <artifactId>plugin-goodbye</artifactId>
                  <version>${project.parent.version}</version>
                  <outputDirectory>${project.build.directory}/plugins</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>org.example.plugin</groupId>
                  <artifactId>plugin-welcome</artifactId>
                  <version>${project.parent.version}</version>
                  <outputDirectory>${project.build.directory}/plugins</outputDirectory>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
